# auto generated, manual changes may be overwritten
USE_LOCAL_CSS=False
LOCAL_CSS_FILE='basic.css'
SYNC_PASSWORD='test'
DEBUG_NETWORK=False
PLAY_COMMAND='play'
DECK_PATH=''
SERVER_PORT=8000
DISPLAY_DIVIDER=True
SYNC_USERNAME='test'
RENDER_LATEX=False
DISPLAY_INTERVAL=True
